CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

ALTER TABLE "User"
ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'USER';

ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."RefreshToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Friendship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Post" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Reaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DailyFrame" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DailyFrameItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."MonthlyCollage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Yearbook" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ShareLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Notification" ENABLE ROW LEVEL SECURITY;
